export const data = [
  {
    id: "9s41rp",
    firstName: "Kelvin",
    lastName: "Langosh",
    email: "Jerod14@hotmail.com",
    age: 19,
    dob: "19-02-1999",
    address: "Lhr",
    phone: "090078601",
  },
  {
    id: "08m6rx",
    firstName: "Molly",
    lastName: "Purdy",
    email: "Hugh.Dach79@hotmail.com",
    age: 37,
    state: "Rhode Island",
    dob: "19-02-1999",
    address: "Lhr",
    phone: "090078601",
  },
  {
    id: "5ymtrc",
    firstName: "Henry",
    lastName: "Lynch",
    email: "Camden.Macejkovic@yahoo.com",
    age: 20,
    state: "California",
    dob: "19-02-1999",
    address: "Lhr",
    phone: "090078601",
  },
  {
    id: "ek5b97",
    firstName: "Glenda",
    lastName: "Douglas",
    email: "Eric0@yahoo.com",
    age: 38,
    state: "Montana",
    dob: "19-02-1999",
    address: "Lhr",
    phone: "090078601",
  },
  {
    id: "xxtydd",
    firstName: "Leone",
    lastName: "Williamson",
    email: "Ericka_Mueller52@yahoo.com",
    age: 19,
    state: "Colorado",
    dob: "19-02-1999",
    address: "Lhr",
    phone: "090078601",
  },
  {
    id: "wzxj9m",
    firstName: "Mckenna",
    lastName: "Friesen",
    email: "Veda_Feeney@yahoo.com",
    age: 34,
    state: "New York",
    dob: "19-02-1999",
    address: "Lhr",
    phone: "090078601",
  },
  {
    id: "21dwtz",
    firstName: "Wyman",
    lastName: "Jast",
    email: "Melvin.Pacocha@yahoo.com",
    age: 23,
    state: "Montana",
    dob: "19-02-1999",
    address: "Lhr",
    phone: "090078601",
  },
  {
    id: "o8oe4k",
    firstName: "Janick",
    lastName: "Willms",
    email: "Delfina12@gmail.com",
    age: 25,
    state: "Nebraska",
    dob: "19-02-1999",
    address: "Lhr",
    phone: "090078601",
  },
];
